import Company from '../models/company.model'
import { Bootstrapper } from './Bootstraper'

export default class CompanyBootstrap extends Bootstrapper {
  async run() {
    await Company.bulkCreate([
      {
        companyId: 'c1b0e7e0-0b1a-4e1a-9f1a-0e5a9a1b0e7e',
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b8',
        name: 'Company 1',
        description: 'Company 1 description',
        email: 'example1@mail.com',
        phone: '123456789',
        webPage: 'www.company1.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company1-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company1-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company1-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company1-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company1-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company1-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'a2b0e7e0-0b1a-4e1a-9f1a-0e5a9a1b0e7e',
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b9',
        name: 'Company 2',
        description: 'Company 2 description',
        email: 'example2@mail.com',
        phone: '123456790',
        webPage: 'www.company2.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company2-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company2-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company2-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company2-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company2-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company2-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'a2c0e7e0-0b1a-4e1a-9f1a-0e5a9a1b0e7e',
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b7',
        name: 'Company 3',
        description: 'Company 3 description',
        email: 'example3@mail.com',
        phone: '123456791',
        webPage: 'www.company3.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company3-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company3-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company3-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company3-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company3-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company3-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0003',
        userId: '5ae3f37e-5313-49f0-b1ec-0050f010067f',
        name: 'Company 4',
        description: 'Company 4 description',
        email: 'example4@mail.com',
        phone: '123456792',
        webPage: 'www.company4.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company4-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company4-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company4-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company4-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company4-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company4-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0004',
        userId: '6381d9cf-6693-49a2-be80-82c82b63d6ca',
        name: 'Company 5',
        description: 'Company 5 description',
        email: 'example5@mail.com',
        phone: '123456793',
        webPage: 'www.company5.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company5-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company5-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company5-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company5-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company5-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company5-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0005',
        userId: '19241612-b373-4238-aa42-d9467a457234',
        name: 'Company 6',
        description: 'Company 6 description',
        email: 'example6@mail.com',
        phone: '123456794',
        webPage: 'www.company6.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company6-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company6-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company6-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company6-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company6-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company6-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0006',
        userId: 'b90edc2f-ec86-4b55-80a8-55dc7873b991',
        name: 'Company 7',
        description: 'Company 7 description',
        email: 'example7@mail.com',
        phone: '123456795',
        webPage: 'www.company7.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company7-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company7-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company7-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company7-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company7-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company7-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0007',
        userId: '05276d35-f433-469e-b3fb-6a310296ea84',
        name: 'Company 8',
        description: 'Company 8 description',
        email: 'example8@mail.com',
        phone: '123456796',
        webPage: 'www.company8.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company8-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company8-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company8-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company8-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company8-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company8-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0008',
        userId: '8dcc93aa-8c69-4519-ae0e-08814226bca7',
        name: 'Company 9',
        description: 'Company 9 description',
        email: 'example9@mail.com',
        phone: '123456797',
        webPage: 'www.company9.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company9-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company9-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company9-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company9-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company9-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company9-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0009',
        userId: '7fa2ee93-21a7-4d2c-9fa2-ae2c312080cf',
        name: 'Company 10',
        description: 'Company 10 description',
        email: 'example10@mail.com',
        phone: '123456798',
        webPage: 'www.company10.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company10-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company10-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company10-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company10-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company10-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company10-ine.pdf',
        status: 'pending_approval',
      },
      {
        companyId: 'comp-1234-efgh-0010',
        userId: 'abcd-1234-efgh-5689',
        name: 'Company 11',
        description: 'Company 11 description',
        email: 'example11@mail.com',
        phone: '123456799',
        webPage: 'www.company11.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company11-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company11-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company11-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company11-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company11-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company11-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0011',
        userId: 'abcd-1234-efgh-5690',
        name: 'Company 12',
        description: 'Company 12 description',
        email: 'example12@mail.com',
        phone: '123456800',
        webPage: 'www.company12.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company12-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company12-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company12-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company12-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company12-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company12-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0012',
        userId: 'abcd-1234-efgh-5691',
        name: 'Company 13',
        description: 'Company 13 description',
        email: 'example13@mail.com',
        phone: '123456801',
        webPage: 'www.company13.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company13-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company13-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company13-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company13-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company13-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company13-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0013',
        userId: 'abcd-1234-efgh-5692',
        name: 'Company 14',
        description: 'Company 14 description',
        email: 'example14@mail.com',
        phone: '123456802',
        webPage: 'www.company14.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company14-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company14-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company14-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company14-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company14-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company14-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0014',
        userId: 'abcd-1234-efgh-5693',
        name: 'Company 15',
        description: 'Company 15 description',
        email: 'example15@mail.com',
        phone: '123456803',
        webPage: 'www.company15.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company15-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company15-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company15-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company15-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company15-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company15-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0015',
        userId: 'abcd-1234-efgh-5694',
        name: 'Company 16',
        description: 'Company 16 description',
        email: 'example16@mail.com',
        phone: '123456804',
        webPage: 'www.company16.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company16-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company16-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company16-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company16-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company16-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company16-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0016',
        userId: 'abcd-1234-efgh-5695',
        name: 'Company 17',
        description: 'Company 17 description',
        email: 'example17@mail.com',
        phone: '123456805',
        webPage: 'www.company17.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company17-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company17-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company17-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company17-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company17-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company17-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0017',
        userId: 'abcd-1234-efgh-5696',
        name: 'Company 18',
        description: 'Company 18 description',
        email: 'example18@mail.com',
        phone: '123456806',
        webPage: 'www.company18.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company18-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company18-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company18-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company18-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company18-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company18-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0018',
        userId: 'abcd-1234-efgh-5697',
        name: 'Company 19',
        description: 'Company 19 description',
        email: 'example19@mail.com',
        phone: '123456807',
        webPage: 'www.company19.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company19-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company19-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company19-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company19-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company19-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company19-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0019',
        userId: 'abcd-1234-efgh-5698',
        name: 'Company 20',
        description: 'Company 20 description',
        email: 'example20@mail.com',
        phone: '123456808',
        webPage: 'www.company20.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company20-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company20-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company20-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company20-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company20-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company20-ine.pdf',
        status: 'approved',
      },
      {
        companyId: 'comp-1234-efgh-0020',
        userId: 'abcd-1234-efgh-5699',
        name: 'Company 21',
        description: 'Company 21 description',
        email: 'example21@mail.com',
        phone: '123456809',
        webPage: 'www.company21.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company21-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company21-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company21-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company21-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company21-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company21-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0021',
        userId: 'abcd-1234-efgh-5700',
        name: 'Company 22',
        description: 'Company 22 description',
        email: 'example22@mail.com',
        phone: '123456810',
        webPage: 'www.company22.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company22-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company22-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company22-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company22-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company22-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company22-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0022',
        userId: 'abcd-1234-efgh-5701',
        name: 'Company 23',
        description: 'Company 23 description',
        email: 'example23@mail.com',
        phone: '123456811',
        webPage: 'www.company23.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company23-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company23-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company23-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company23-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company23-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company23-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0023',
        userId: 'abcd-1234-efgh-5702',
        name: 'Company 24',
        description: 'Company 24 description',
        email: 'example24@mail.com',
        phone: '123456812',
        webPage: 'www.company24.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company24-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company24-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company24-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company24-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company24-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company24-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0024',
        userId: 'abcd-1234-efgh-5703',
        name: 'Company 25',
        description: 'Company 25 description',
        email: 'example25@mail.com',
        phone: '123456813',
        webPage: 'www.company25.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company25-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company25-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company25-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company25-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company25-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company25-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0025',
        userId: 'abcd-1234-efgh-5704',
        name: 'Company 26',
        description: 'Company 26 description',
        email: 'example26@mail.com',
        phone: '123456814',
        webPage: 'www.company26.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company26-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company26-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company26-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company26-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company26-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company26-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0026',
        userId: 'abcd-1234-efgh-5705',
        name: 'Company 27',
        description: 'Company 27 description',
        email: 'example27@mail.com',
        phone: '123456815',
        webPage: 'www.company27.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company27-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company27-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company27-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company27-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company27-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company27-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0027',
        userId: 'abcd-1234-efgh-5706',
        name: 'Company 28',
        description: 'Company 28 description',
        email: 'example28@mail.com',
        phone: '123456816',
        webPage: 'www.company28.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company28-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company28-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company28-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company28-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company28-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company28-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0028',
        userId: 'abcd-1234-efgh-5707',
        name: 'Company 29',
        description: 'Company 29 description',
        email: 'example29@mail.com',
        phone: '123456817',
        webPage: 'www.company29.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company29-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company29-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company29-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company29-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company29-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company29-ine.pdf',
        status: 'rejected',
      },
      {
        companyId: 'comp-1234-efgh-0029',
        userId: 'abcd-1234-efgh-5708',
        name: 'Company 30',
        description: 'Company 30 description',
        email: 'example30@mail.com',
        phone: '123456818',
        webPage: 'www.company30.com',
        street: '123 Main Street',
        streetNumber: '456',
        city: 'Cityville',
        state: 'Stateville',
        zipCode: '12345',
        profilePicture:
          'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6XZP6rdW3VhHwZSxu3u4RCWyQFHTwl_4QSRK5t0km1FCytdaWwJEoNmW8c2ju5DRR4DbxppAQvVH441I',
        pdfCurriculumUrl: 'https://example.com/company30-cv.pdf',
        pdfDicCdmxUrl: 'https://example.com/company30-dic-cdmx.pdf',
        pdfPeeFideUrl: 'https://example.com/company30-pee-fide.pdf',
        pdfGuaranteeSecurityUrl:
          'https://example.com/company30-guarantee-security.pdf',
        pdfActaConstitutivaUrl:
          'https://example.com/company30-acta-constitutiva.pdf',
        pdfIneUrl: 'https://example.com/company30-ine.pdf',
        status: 'rejected',
      },
    ])
  }
}
