import User from '../models/users.model'
import { Bootstrapper } from './Bootstraper'

export default class UserBootstrap extends Bootstrapper {
  async run() {
    await User.bulkCreate([
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b8',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '8453728592',
        age: 30,
        state: 'NY',
        gender: 'masculine',
        deviceToken: '',
      },
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b9',
        roleId: 'CUSTOMER_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0987654321',
        age: 25,
        state: 'CA',
        gender: 'femenine',
      },
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b7',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Sergio',
        lastName: 'Garnica González',
        email: 'a01704025@tec.mx',
        phoneNumber: '4424396065',
        age: 22,
        state: 'QRO',
        gender: 'masculine',
      },
      {
        userId: '191aa15f-7c2d-411c-8bc9-0114bbc3b0ed',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        googleId: null,
        facebookId: null,
        appleId: null,
        firstName: 'Yolanda',
        lastName: 'Chavez',
        secondLastName: null,
        email: 'test@test.com',
        password:
          '$2b$10$dfHFSk6jF0yEs6SUo1LCEuJGLTn0DofEo7ZwmNYzajUPyL/Cwxjtu',
        salt: '$2b$10$dfHFSk6jF0yEs6SUo1LCEu',
        phoneNumber: '0123456789',
        age: 21,
        state: 'Veracruz',
        gender: 'other',
        deviceToken: null,
        profilePicture: null,
      },
    ])
  }
}
