import User from '../models/users.model'
import { Bootstrapper } from './Bootstraper'

export default class UserBootstrap extends Bootstrapper {
  async run() {
    await User.bulkCreate([
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b8',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '1234567890',
        age: 30,
        state: 'NY',
        gender: 'masculine',
      },
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b9',
        roleId: 'CUSTOMER_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0987654321',
        age: 25,
        state: 'CA',
        gender: 'femenine',
      },
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b7',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Sergio',
        lastName: 'Garnica González',
        email: 'a01704025@tec.mx',
        phoneNumber: '4424396065',
        age: 22,
        state: 'QRO',
        gender: 'masculine',
      },
      {
        userId: '5ae3f37e-5313-49f0-b1ec-0050f010067f',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Jake',
        lastName: 'Doe',
        email: 'jake.doe@example.com',
        phoneNumber: '0987654322',
        age: 25,
        state: 'CA',
        gender: 'masculine',
      },
      {
        userId: '6381d9cf-6693-49a2-be80-82c82b63d6ca',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Mark',
        lastName: 'Doe',
        email: 'mark.doe@example.com',
        phoneNumber: '0987654323',
        age: 25,
        state: 'CA',
        gender: 'masculine',
      },
      {
        userId: '19241612-b373-4238-aa42-d9467a457234',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Chris',
        lastName: 'Doe',
        email: 'chris.doe@example.com',
        phoneNumber: '0987654324',
        age: 25,
        state: 'CA',
        gender: 'masculine',
      },
      {
        userId: 'b90edc2f-ec86-4b55-80a8-55dc7873b991',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Jenny',
        lastName: 'Doe',
        email: 'jenny.doe@example.com',
        phoneNumber: '0987654325',
        age: 25,
        state: 'CA',
        gender: 'femenine',
      },
      {
        userId: '05276d35-f433-469e-b3fb-6a310296ea84',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Lucy',
        lastName: 'Doe',
        email: 'lucy.doe@example.com',
        phoneNumber: '0987654326',
        age: 25,
        state: 'CA',
        gender: 'femenine',
      },
      {
        userId: '8dcc93aa-8c69-4519-ae0e-08814226bca7',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Pedro',
        lastName: 'Doe',
        email: 'pedro.doe@example.com',
        phoneNumber: '0987654327',
        age: 25,
        state: 'CA',
        gender: 'masculine',
      },
      {
        userId: '7fa2ee93-21a7-4d2c-9fa2-ae2c312080cf',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Troy',
        lastName: 'Doe',
        email: 'troy.doe@example.com',
        phoneNumber: '0987654328',
        age: 25,
        state: 'CA',
        gender: 'masculine',
      },
      {
        userId: '576adbc1-4a87-4674-bd82-7b8c32613c64',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Sophia',
        lastName: 'Doe',
        email: 'sophia.doe@example.com',
        phoneNumber: '0987654329',
        age: 25,
        state: 'CA',
        gender: 'femenine',
      },
      {
        userId: '576adbc1-4a87-4671-bd82-7b8c32613c64',
        roleId: 'ADMIN_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Ana',
        lastName: 'Doe',
        email: 'ana.doe@example.com',
        phoneNumber: '0987654330',
        age: 25,
        state: 'CA',
        gender: 'femenine',
      },
    ])
  }
}
