import User from '../models/users.model'
import { Bootstrapper } from './Bootstraper'

export default class UserBootstrap extends Bootstrapper {
  async run() {
    await User.bulkCreate([
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b8',
        roleId: 'COMAPNY_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '8453728592',
        age: 30,
        state: 'NY',
        gender: 'masculine',
        deviceToken: '',
      },
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b9',
        roleId: 'COMAPNY_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        password: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        phoneNumber: '0987654321',
        age: 25,
        state: 'CA',
        gender: 'femenine',
      },
      {
        userId: '8de45630-2e76-4d97-98c2-9ec0d1f3a5b7',
        roleId: 'COMAPNY_ROLE_ID',
        companyId: null,
        appleId: null,
        facebookId: null,
        googleId: null,
        profilePicture: null,
        secondLastName: null,
        firstName: 'Sergio',
        lastName: 'Garnica González',
        email: 'company@test.com',
        password:
          '$2b$10$dfHFSk6jF0yEs6SUo1LCEuJGLTn0DofEo7ZwmNYzajUPyL/Cwxjtu',
        salt: '$2b$10$dfHFSk6jF0yEs6SUo1LCEu',
        phoneNumber: '4424396065',
        age: 22,
        state: 'QRO',
        gender: 'masculine',
      },
      {
        userId: '191aa15f-7c2d-411c-8bc9-0114bbc3b0ed',
        roleId: 'CUSTOMER_ROLE_ID',
        companyId: null,
        googleId: null,
        facebookId: null,
        appleId: null,
        firstName: 'Yolanda',
        lastName: 'Chavez',
        secondLastName: null,
        email: 'test@greencircleadmin.com',
        password:
          '$2b$10$dfHFSk6jF0yEs6SUo1LCEuJGLTn0DofEo7ZwmNYzajUPyL/Cwxjtu',
        salt: '$2b$10$dfHFSk6jF0yEs6SUo1LCEu',
        phoneNumber: '0123456789',
        age: 21,
        state: 'Veracruz',
        gender: 'other',
        deviceToken: null,
        profilePicture: null,
      },
      {
        userId: 'b5beb2ca-10da-4b78-a058-d417a7dc96a6',
        roleId: 'ADMIN_ROLE_ID',
        firstName: 'Administrador',
        lastName: '1',
        email: 'Admin1@greencircleadmin.com',
        password:
          '$2b$10$GChSjDJx8xzYxdFGI.1guegXmO28VkCXKF7S/LRwHbpa2hzWlmPOW',
        salt: '$2b$10$GChSjDJx8xzYxdFGI.1gue',
        age: 21,
        state: 'Queretaro',
        gender: 'other',
      },
      {
        userId: '6968d65a-1ae5-4c20-8b8c-1ae3798fded5',
        roleId: 'ADMIN_ROLE_ID',
        firstName: 'Administrador',
        lastName: '2',
        email: 'Admin2@greencircleadmin.com',
        password:
          '$2b$10$I0cx/g4dxqWQSquczdrSBOPaqK/o/nFsR6rudGZoaM2fHt9CsOZG.',
        salt: '$2b$10$I0cx/g4dxqWQSquczdrSBO',
        age: 21,
        state: 'Queretaro',
        gender: 'other',
      },
      {
        userId: 'ad90a6af-dde5-43fa-b9e0-2a48c45466e2',
        roleId: 'ADMIN_ROLE_ID',
        firstName: 'Administrador',
        lastName: '3',
        email: 'Admin3@greencircleadmin.com',
        password:
          '$2b$10$e9R5/gEt/m91F4JaMyQLj./35jm1SA19E8yk4swXETWn0xxc8W3fq',
        salt: '$2b$10$e9R5/gEt/m91F4JaMyQLj.',
        age: 21,
        state: 'Queretaro',
        gender: 'other',
      },
      {
        userId: '80258658-062a-466d-869e-266f336642fa',
        roleId: 'ADMIN_ROLE_ID',
        firstName: 'Administrador',
        lastName: '4',
        email: 'Admin4@greencircleadmin.com',
        password:
          '$2b$10$CYHNiDhDvE6tjdXI2cp8C.2IC9bPJUpemXA1fP6mnpCAyBNK2ZCbu',
        salt: '$2b$10$CYHNiDhDvE6tjdXI2cp8C.',
        age: 21,
        state: 'Queretaro',
        gender: 'other',
      },
      {
        userId: 'cbfb2951-9a62-4576-9c1e-cf15a590ac94',
        roleId: 'ADMIN_ROLE_ID',
        firstName: 'Administrador',
        lastName: '5',
        email: 'Admin5@greencircleadmin.com',
        password:
          '$2b$10$htHvc.B2nF2nlqHdfPkzjuXFwdhiCDqo9vcIHgxdZ9ImqYodiogma',
        salt: '$2b$10$htHvc.B2nF2nlqHdfPkzju',
        age: 21,
        state: 'Queretaro',
        gender: 'other',
      },
    ])
  }
}
